### ISSUE TITLE
Typo in the description

### ISSUE THREAD

**Issue by siiky** [standardebooks/nikolai-gogol_dead-souls_d-j-hogarth#4]
> (...) in his attempts to cheat the both the system and the cavalcade of townspeople (...)

https://github.com/standardebooks/nikolai-gogol_dead-souls_d-j-hogarth/blob/820f6a8e1bad8cd18146e4f55379017e2f54e59d/src/epub/content.opf#L48

And can be read on the site: https://standardebooks.org/ebooks/nikolai-gogol/dead-souls/d-j-hogarth

I imagine there's more to do than just change the text, but don't know what; that's why I'm not sending a PR myself.

**Comment by acabal** [comment]
Thanks, this should be fixed now. A pull request updating this repo is all that we need, everything else is updated automatically.

**Comment by siiky** [comment]
Oh I didn't know that, that's awesome! I'll make a PR next time, then.
